<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Jellyfin.Plugin.TreasureMaps</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.TreasureMaps</AssemblyName>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Version>1.0.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <!-- Provides ASP.NET Core (controllers) and Microsoft.Extensions.Http (IHttpClientFactory). -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MediaBrowser.Controller\MediaBrowser.Controller.csproj" Private="false" />
    <ProjectReference Include="..\..\MediaBrowser.Model\MediaBrowser.Model.csproj" Private="false" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Configuration\config.html" />
    <EmbeddedResource Include="Configuration\config.html" />
  </ItemGroup>

</Project>
